name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: wut-daas/uav-assess-vr
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: cd docs && npm install && npm run build
        BUILD_DIR: src/.vuepress/dist/